# R training resources {#training-resources}

## Introductory R learning resources

Welcome to `R`! There are so many learning resources out there it can feel a little overwhelming in terms of what to choose! Right now, we REALLY like [this short intro course](https://rstudio-conf-2020.github.io/r-for-excel/) by [`@juliesquid`](https://twitter.com/juliesquid) & [`@allisonhorst`](https://twitter.com/allisonhorst). They teach a lot of the workflow and tools around using R right from the get go, which we think is more helpful than knowing how to do all the things. The (excellent) materials are thoughtfully put together, link to a ton of other great resources, and just like the online #rstats community in general, are super supportive of new learners.  

If you want a book to work from/through, [R for Data Science](r4ds.had.co.nz) is highly recommended.  (book is free online)  

A plug for the online R community. Follow the hashtag [#rstats](https://twitter.com/search?q=%23rstats), & also check out accounts [`@RLadiesGlobal`](https://twitter.com/RLadiesGlobal) & [`@R4dsCommunity`](https://twitter.com/R4dsCommunity). The weekly #TidyTuesday social coding project is also a great way to practice your growing R skills. Have fun!  

[RStudio Community](https://community.rstudio.com/)  
[stat545.com](stat545.com)  
[Data science in a box](datasciencebox.org)  
[swirlstats.com](swirlstats.com)  
[carpentries R lessons](https://datacarpentry.org/R-ecology-lesson/)

